const orbType = Math.round(Math.random() * 2);
if(orbType = 1){
  document.getElementById("a").innerText = "dungeon";
  const seed = Math.round(Math.random() * 1000000000);
  document.getElementById("a").href = "watabou.github.io/one-page-dungeon/?seed=" + window.location.search.split(8);
  document.getElementById("ifr").src = "watabou.github.io/one-page-dungeon/?seed=" + window.location.search.split(8);
} else {
  document.getElementById("a").innerText = "entity" + encounter;
}

class RandomEncounterGenerator {
    constructor(seed) {
        this.seed = window.location.search.split(8);
        this.random = this.createRandom(seed);
    }

    createRandom(seed) {
        const x = Math.sin(seed) * 10000;
        return () => x - Math.floor(x);
    }

    rollDie(sides) {
        return Math.floor(this.random() * sides) + 1;
    }

    getRandomMonster() {
        const monsters = [
            { name: "grid bug", challenge: 1 },
          { name: "jackal", challenge: 1 },
          { name: "kobold zombie", challenge: 1 },
          { name: "newt", challenge: 1 },
          { name: "sewer rat", challenge: 1 },
          { name: "fox", challenge: 1 },
          { name: "lichen", challenge: 1 },
          { name: "goblin", challenge: 1 },
          { name: "kobold", challenge: 1 },
          { name: "bat", challenge: 2 },
          { name: "human", challenge: 2 },
          { name: "cyote", challenge: 2 },
          { name: "gecko", challenge: 2 },
          { name: "giant rat", challenge: 2 },
          { name: "gnome zombie", challenge: 2 },
          { name: "yellow mold", challenge: 2 },
          { name: "acid blob", challenge: 2 },
          { name: "brown mold", challenge: 2 },
          { name: "green mold", challenge: 2 },
          { name: "red mold", challenge: 2 },
          { name: "gas spore", challenge: 2 },
          { name: "hobbit", challenge: 2 },
          { name: "large kobold", challenge: 2 },
          { name: "shrieker", challenge: 2 },
          { name: "cave spider", challenge: 3 },
          { name: "garter snake", challenge: 3 },
          { name: "manes", challenge: 3 },
          { name: "gnome", challenge: 3 },
          { name: "hobgoblin", challenge: 3 },
          { name: "Keystone Kop", challenge: 3 },
          { name: "orc", challenge: 3 },
          { name: "dwarf zombie", challenge: 3 },
          { name: "floating eye", challenge: 3 },
          { name: "iguana", challenge: 3 },
          { name: "orc zombie", challenge: 3 },
          { name: "homunculus", challenge: 3 },
          { name: "kitten", challenge: 3 },
          { name: "little dog", challenge: 3 },
          { name: "giant bat", challenge: 3 },
          { name: "kobold lord", challenge: 3 },
          { name: "werejackal", challenge: 3 + (1/2) },
          { name: "wererat", challenge: 3 + (1/2) },
          { name: "monkey", challenge: 4 },
          { name: "rabid rat", challenge: 4 },
          { name: "rothe", challenge: 4 },
          { name: "centipede", challenge: 4 },
          { name: "giant ant", challenge: 4 },
          { name: "dwarf", challenge: 4 },
          { name: "Kop Sergeant", challenge: 4 },
          { name: "kobold shamen", challenge: 4 },
          { name: "baby crocodile", challenge: 4 },
          { name: "black naga hatchling", challenge: 4 },
          { name: "elf zombie", challenge: 4 },
          { name: "golden naga hatchling", challenge: 4 },
          { name: "gray ooze", challenge: 4 },
          { name: "gaurdian naga hatchling", challenge: 4 },
          { name: "kobold mummy", challenge: 4 },
          { name: "paper golem", challenge: 4 },
          { name: "red naga hatching", challenge: 4 },
          { name: "rock piercer", challenge: 4 },
          { name: "straw golem", challenge: 4 },
          { name: "pony", challenge: 4 },
          { name: "gnome lord", challenge: 4 },
          { name: "rock mole", challenge: 4 },
          { name: "woodchuck", challenge: 4 },
          { name: "fog cloud", challenge: 4 },
          { name: "leprechaun", challenge: 4 },
          { name: "killer bee", challenge: 5 },
          { name: "ghoul", challenge: 5 },
          { name: "lemure", challenge: 5 },
          { name: "mountain nymph", challenge: 5 },
          { name: "water nymph", challenge: 5 },
          { name: "wood nymph", challenge: 5 },
          { name: "bugbear", challenge: 5 },
          { name: "Kop Lieutenant", challenge: 5 },
          { name: "mordor orc", challenge: 5 },
          { name: "Uruk-hai", challenge: 5 },
          { name: "jellyfish", challenge: 5 },
          { name: "violet fungus", challenge: 5 },
          { name: "gnomish wizard", challenge: 5 },
          { name: "orc shaman", challenge: 5 },
          { name: "gnome mummy", challenge: 5 },
          { name: "human zombie", challenge: 5 },
          { name: "yellow light", challenge: 5 },
          { name: "dingo", challenge: 5 },
          { name: "dog", challenge: 5 },
          { name: "housecat", challenge: 5 },
          { name: "blue jelly", challenge: 5 },
          { name: "fire ant", challenge: 6 },
          { name: "soldier ant", challenge: 6 },
          { name: "ape", challenge: 6 },
          { name: "jaguar", challenge: 6 },
          { name: "rope golem", challenge: 6 },
          { name: "Kop Kaptain", challenge: 6 },
          { name: "raven", challenge: 6 },
          { name: "Woodland-elf", challenge: 6 },
          { name: "snake", challenge: 6 },
          { name: "plains centaur", challenge: 6 },
          { name: "dwarf lord", challenge: 6 },
          { name: "black unicorn", challenge: 6 },
          { name: "gray unicorn", challenge: 6 },
          { name: "white unicorn", challenge: 6 },
          { name: "dust vortex", challenge: 6 },
          { name: "brown pudding", challenge: 6 },
          { name: "dwarf mummy", challenge: 6 },
          { name: "giant beetle", challenge: 6 },
          { name: "gold golem", challenge: 6 },
          { name: "lizard", challenge: 6 },
          { name: "orc mummy", challenge: 6 },
          { name: "piranha", challenge: 6 },
          { name: "wolf", challenge: 6 },
          { name: "quivering blob", challenge: 6 },
          { name: "gnome king", challenge: 6 },
          { name: "spotted jelly", challenge: 6 },
          { name: "werewolf", challenge: 6.5 },
          { name: "iron piercer", challenge: 6 },
          { name: "quasit", challenge: 7 },
          { name: "water moccasin", challenge: 7 },
          { name: "lynx", challenge: 7 },
          { name: "panther", challenge: 7 },
          { name: "yeti", challenge: 7 },
          { name: "attendant", challenge: 7 },
          { name: "chieftain", challenge: 7 },
          { name: "Green-elf", challenge: 7 },
          { name: "horse", challenge: 7 },
          { name: "hunter", challenge: 7 },
          { name: "neanderthal", challenge: 7 },
          { name: "ogre", challenge: 7 },
          { name: "student", challenge: 7 },
          { name: "giant spider", challenge: 7 },
          { name: "winter wolf cub", challenge: 7 },
          { name: "ninja", challenge: 7 },
          { name: "orc-captain", challenge: 7 },
          { name: "page", challege: 7 },
          { name: "roshi", chalenge: 7 },
          { name: "thug", challenge: 7 },
          { name: "vampire bat", challenge: 7 },
          { name: "warrior", challenge: 7 },
          { name: "mumak", challenge: 7 },
          { name: "black light", challenge: 7 },
          { name: "chameleon", challenge: 7 },
          { name: "crocodile", challenge: 7 },
          { name: "elf mummy", challenge: 7 },
          { name: "ettin zombie", challenge: 7 },
          { name: "human mummy", challenge: 7 },
          { name: "leather golem", challenge: 7 },
          { name: "ice vortex", challenge: 7 },
          { name: "large cat", challenge: 7 },
          { name: "large dog", challenge: 7 },
          { name: "tengu", challenge: 7 },
          { name: "barrow wight", challenge: 7 },
          { name: "owlbear", challenge: 7 },
          { name: "chickatrice", challenge: 7 },
          { name: "giant eel", challenge: 7 },
          { name: "gremlin", challenge: 8 },
          { name: "forest centaur", challenge: 8 },
          { name: "abbot", challenge: 8 },
          { name: "scorpion", challenge: 8 },
          { name: "acolyte", challenge: 8 },
          { name: "apprentice", challenge: 8 },
          { name: "guide", challenge: 8 },
          { name: "rust monster", challenge: 8 },
          { name: "tiger", challenge: 8 },
          { name: "carnivourious ape", challenge: 8 },
          { name: "gelatinous cube", challenge: 8 },
          { name: "leocrotta", challenge: 8 },
          { name: "Grey-elf", challenge: 8 },
          { name: "soldier", challenge: 8 },
          { name: "watchman", challenge: 8 },
          { name: "gargoyle", challenge: 8 },
          { name: "pyrolisk", challenge: 8 },
          { name: "python", challenge: 8 },
          { name: "red naga", challenge: 8 },
          { name: "dwarf king", challenge: 8 },
          { name: "ochre jelly", challenge: 8 },
          { name: "flaming sphere", challenge: 8 },
          { name: "freezing sphere", challenge: 8 },
          { name: "shocking sphere", challenge: 8 },
          { name: "ettin mummy", chalenge: 8 },
          { name: "small mimic", challenge: 8 },
          { name: "warg", challenge: 8 },
          { name: "wood golem", challenge: 8 },
          { name: "djinni", challenge: 8 },
          { name: "wraith", challenge: 8 },
          { name: "incubus", challenge: 8 },
          { name: "succubus", challenge: 8 },
          { name: "giant", challenge: 8 },
          { name: "stone giant", challenge: 8 },
          { name: "cockatrice", challenge: 8 },
          { name: "green slime", challenge: 8 },
          { name: "mountain centaur", challenge: 9 },
          { name: "quantum mechanic", challenge: 9 },
          { name: "pit viper", challenge: 9 },
          { name: "sasquatch", challenge: 9 },
          { name: "ogre lord", challenge: 9 },
          { name: "troll", challenge: 9 },
          { name: "warhorse", challenge: 9 },
          { name: "energy vortex", challenge: 9 },
          { name: "hell hound pup", challenge: 9 },
          { name: "winter wolf", challenge: 9 },
          { name: "xan", challenge: 9 },
          { name: "glass piercer", challenge: 9 },
          { name: "shark", challenge: 9 },
          { name: "baby long worm", challenge: 9 },
          { name: "baby purple worm", challenge: 9 },
          { name: "giant zombie", challenge: 9 },
          { name: "large mimic", challenge: 9 },
          { name: "stalker", challenge: 9 },
          { name: "steam vortex", challenge: 9 },
          { name: "wampus", challenge: 9 },
          { name: "horned devil", challenge: 9 },
          { name: "long worm", challenge: 9 },
          { name: "cobra", challenge: 10 },
          { name: "giant mummy", challenge: 10 },
          { name: "sergeant", challenge: 10 },
          { name: "air elemental", challenge: 10 },
          { name: "earth elemental", challenge: 10 },
          { name: "water elemental", challenge: 10 },
          { name: "black naga", challenge: 10 },
          { name: "fire elemental", challenge: 10 },
          { name: "fire vortex", challenge: 10 },
          { name: "erinys", challenge: 10 },
          { name: "hill giant", challenge: 10 },
          { name: "barbed devil", challenge: 10 },
          { name: "flesh golem", challenge: 10 },
          { name: "electric eel", challenge: 10 },
          { name: "elf-lord", challenge: 11 },
          { name: "xorn", challenge: 11 },
          { name: "marilith", challenge: 11 },
          { name: "vrock", challenge: 11 },
          { name: "couatl", challenge: 11 },
          { name: "water demon", challenge: 11 },
          { name: "giant mimic", challenge: 11 },
          { name: "zruty", challenge: 11 },
          { name: "doppelganger", challenge: 11 },
          { name: "ogre king", chalenge: 11 },
          { name: "winged gargoyle", challenge: 11 },
          { name: "Elvenking", challenge: 11 },
          { name: "monk", challenge: 11 },
          { name: "fire giant", challenge: 11 },
          { name: "salamander", challenge: 12 },
          { name: "umber hulk", challenge: 12 },
          { name: "rock troll", challenge: 12 },
          { name: "ice troll", challenge: 12 },
          { name: "queen bee", challenge: 12 },
          { name: "lurker above", challenge: 12 },
          { name: "caveman", challenge: 12 },
          { name: "cavewoman", challenge: 12 },
          { name: "elf", challenge: 12 },
          { name: "healer", challenge: 12 },
          { name: "priest", challenge: 12 },
          { name: "priestess", challenge: 12 },
          { name: "ranger", challenge: 12 },
          { name: "wizard", challenge: 12 },
          { name: "ghost", challenge: 12 },
          { name: "archeolgist", challenge: 12 },
          { name: "barbarian", challenge: 12 },
          { name: "black pudding", challenge: 12 },
          { name: "knight", challenge: 12 },
          { name: "lieutenant", challenge: 12 },
          { name: "rogue", challenge: 12 },
          { name: "samurai", challenge: 12 },
          { name: "tourist", challenge: 12 },
          { name: "valkyrie", challenge: 12 },
          { name: "watch captain", challenge: 12 },
          { name: "clay golem", challenge: 12 },
          { name: "hezrou", challenge: 12 },
          { name: "Aleax", challenge: 12 },
          { name: "vampire", challenge: 12 },
          { name: "golden naga", challenge: 13 },
          { name: "nurse", challenge: 13 },
          { name: "water troll", challenge: 13 },
          { name: "mind flayer", challenge: 13 },
          { name: "titanothere", challenge: 13 },
          { name: "baby black dragon", challenge: 13 },
          { name: "baby blue dragon", challenge: 13 },
          { name: "baby gray dragon", challenge: 13 },
          { name: "baby green dragon", challenge: 13 },
          { name: "baby orange dragon", challenge: 13 },
          { name: "baby red dragon", challenge: 13 },
          { name: "baby silver dragon", challenge: 13 },
          { name: "baby white dragon", challenge: 13 },
          { name: "baby yellow dragon", challenge: 13 },
          { name: "bone devil", challenge: 13 },
          { name: "Oracle", challenge: 13 },
          { name: "ettin", challenge: 13 },
          { name: "frost giant", challenge: 13 },
          { name: "lich", challenge: 14 },
          { name: "trapper", challenge: 14 },
          { name: "prisoner", challenge: 14 },
          { name: "disenchanter", challenge: 14 },
          { name: "captain", challenge: 14 },
          { name: "guard", challenge: 14 },
          { name: "hell hound", challenge: 14 },
          { name: "ice devil", challenge: 14 },
          { name: "shade", challenge: 14 },
          { name: "skeleton", challenge: 14 },
          { name: "vampire lord", challenge: 14 },
          { name: "shopkeeper", challenge: 15 },
          { name: "aligned priest", challenge: 15 },
          { name: "sandestin", challenge: 15 },
          { name: "baluchitherium", challenge: 15 },
          { name: "nalfeshnee", challenge: 15 },
          { name: "stone golem", challenge: 15 },
          { name: "gaurdian naga", challenge: 16 },
          { name: "Olog-hai", challenge: 16 },
          { name: "pit fiend", challenge: 16 },
          { name: "Nazgul", challenge: 17 },
          { name: "purple worm", challenge: 17 },
          { name: "Scorpius", challenge: 17 },
          { name: "minotaur", challenge: 17 },
          { name: "demilich", challenge: 18 },
          { name: "glass golem", challenge: 18 },
          { name: "jabberwock", challenge: 18 },
          { name: "Vlad the Impaler", challenge: 18 },
          { name: "master mind flayer", challenge: 19 },
          { name: "Angel", challenge: 19 },
          { name: "Ashikaga Takauji", challenge: 19 },
          { name: "Lord Surtur", challenge: 19 },
          { name: "storm giant", challenge: 19 },
          { name: "Dark One", challenge: 20 },
          { name: "Master Assassin", challenge: 20 },
          { name: "black dragon", challenge: 20 },
          { name: "blue dragon", challenge: 20 },
          { name: "gray dragon", challenge: 20 },
          { name: "green dragon", challenge: 20 },
          { name: "orange dragon", challenge: 20 },
          { name: "red dragon", challenge: 20 },
          { name: "silver dragon", challenge: 20 },
          { name: "white dragon", challenge: 20 },
          { name: "yellow dragon", challenge: 20 },
          { name: "titan", challenge: 20 },
          { name: "belrog", challenge: 20 },
          { name: "master lich", challenge: 21 },
          { name: "ki-rin", challenge: 21 },
          { name: "lxoth", challenge: 22 },
          { name: "iron golem", challenge: 22 },
          { name: "Thoth Amon", challenge: 22 },
          { name: "Twoflower", challenge: 22 },
          { name: "Hippocrates", challenge: 22 },
          { name: "Lord Carnarvon", challenge: 22 },
          { name: "Orion", challenge: 22 },
          { name: "Pelias", challenge: 22 },
          { name: "Shaman Karnov", challenge: 22 },
          { name: "mastodon", challenge: 22 },
          { name: "Croesus", challenge: 22 },
          { name: "kraken", challenge: 22 },
          { name: "Minion of Huhetotl", challenge: 23 },
          { name: "Nalzok", challenge: 23 },
          { name: "Chromatic Dragon", challenge: 23 },
          { name: "King Arthur", chalenge: 23 },
          { name: "Lord Sato", challenge: 23 },
          { name: "Norn", challenge: 23 },
          { name: "Neferet the Green", challenge: 23 },
          { name: "Cyclops", challenge: 23 },
          { name: "Master of Thives", challenge: 24 },
          { name: "Medusa", challenge: 25 },
          { name: "mail daemon", challenge: 26 },
          { name: "Archon", challenge: 26 },
          { name: "Juiblex", challenge: 26 },
          { name: "arch-lich", challenge: 29 },
          { name: "Arch Priest", challenge: 30 },
          { name: "Grand Master", challenge: 30 },
          { name: "high priest", challenge: 30 },
          { name: "Yeenoghu", challenge: 31 },
          { name: "Master Kaen", challenge: 31 },
          { name: "Wizard of Yendor", challenge: 34 },
          { name: "Death", challenge: 34 },
          { name: "Famine", challenge: 34 },
          { name: "Pestilence", challenge: 34 },
          { name: "Orcus", challenge: 36 },
          { name: "Geryon", challenge: 36 },
          { name: "Dispater", challenge: 40 },
          { name: "Baalzebub", challenge: 45 },
          { name: "Asmodeus", challenge: 53 },
          { name: "Demogorgon", challenge: 57 }
        ];
        const index = this.rollDie(monsters.length) - 1;
        return monsters[index];
    }

    generateEncounter() {
        const numMonsters = this.rollDie(3); // Roll 1d3 for number of monsters
        const encounter = [];

        for (let i = 0; i < numMonsters; i++) {
            encounter.push(this.getRandomMonster());
        }

        return encounter;
    }
}
const encounter = encounterGenerator.generateEncounter();
